-- 1. Create table
create table public.files (
  id bigint generated by default as identity not null,
  file_name text not null,
  folder_path text not null,
  s3_url text not null,
  content_type text null,
  uploaded_at timestamp with time zone not null default timezone ('utc'::text, now()),
  is_deleted boolean not null default false,
  constraint files_pkey primary key (id)
) TABLESPACE pg_default;

-- Note: To apply this to an existing Supabase table, run:
-- ALTER TABLE public.files ADD COLUMN is_deleted BOOLEAN NOT NULL DEFAULT FALSE;

-- 2. Create index for folder path queries
create index IF not exists idx_files_folder_path on public.files using btree (folder_path) TABLESPACE pg_default;

-- 3. Create unique index for folder path and file name
create unique INDEX IF not exists idx_files_unique_path_file on public.files using btree (folder_path, file_name) TABLESPACE pg_default;

-- 4. Enable Supabase Row Level Security (RLS)
ALTER TABLE public.files ENABLE ROW LEVEL SECURITY;
