-- 1. Create table
CREATE TABLE files (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file_name TEXT NOT NULL,
    folder_path TEXT NOT NULL,
    s3_url TEXT NOT NULL,
    content_type TEXT NULL,
    uploaded_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', now())
);

-- 2. Create index for folder path queries
CREATE INDEX idx_files_folder_path ON files (folder_path);

-- 3. Enable Supabase Row Level Security (RLS)
ALTER TABLE files ENABLE ROW LEVEL SECURITY;
